---
language: go
go:
  - release
  - 1.3
  - 1.2

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq librrd-dev

script:
  - make test

notifications:
  email:
    - dev@facette.io

# vim: ts=2 sw=2 et
